# Autogenerated wrapper script for TestU01_jll for x86_64-apple-darwin
export libprobdist, libtestu01, libtestu01extractors

JLLWrappers.@generate_wrapper_header("TestU01")
JLLWrappers.@declare_library_product(libprobdist, "@rpath/libprobdist.0.dylib")
JLLWrappers.@declare_library_product(libtestu01, "@rpath/libtestu01.0.dylib")
JLLWrappers.@declare_library_product(libtestu01extractors, "@rpath/libtestu01extractors.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libprobdist,
        "lib/libprobdist.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtestu01,
        "lib/libtestu01.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtestu01extractors,
        "lib/libtestu01extractors.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
