# Autogenerated wrapper script for TestU01_jll for x86_64-w64-mingw32
export libprobdist, libtestu01, libtestu01extractors

JLLWrappers.@generate_wrapper_header("TestU01")
JLLWrappers.@declare_library_product(libprobdist, "libprobdist-0.dll")
JLLWrappers.@declare_library_product(libtestu01, "libtestu01-0.dll")
JLLWrappers.@declare_library_product(libtestu01extractors, "libtestu01extractors.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libprobdist,
        "bin\\libprobdist-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtestu01,
        "bin\\libtestu01-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtestu01extractors,
        "bin\\libtestu01extractors.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
